swagger: "2.0"
info:
  description: "Swagger doc for connections app"
  version: "1.0.0"
  title: "Connections"
schemes:
- "https"
- "http"
paths:
  /people:
    get:
      summary: "Get list of people"
      description: ""
      operationId: "getPeople"
      produces:
      - "application/json"
      responses:        
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Person"
        400:
          description: "Invalid input"
    post:
      summary: "Create a new person"
      description: ""
      operationId: "createPerson"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Person object that needs to be created"
        required: true
        schema:
          $ref: "#/definitions/NewPerson"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "object"
            items:
              $ref: "#/definitions/Person"
        400:
          description: "Invalid input"
  /connections:
    get:
      summary: "Get list of connections"
      description: ""
      operationId: "getConnections"
      produces:
      - "application/json"
      responses:        
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/NestedConnection"
        400:
          description: "Invalid input"
    post:
      summary: "Create a new connection"
      description: ""
      operationId: "createConnection"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Connection object that needs to be created"
        required: true
        schema:
          $ref: "#/definitions/NewConnection"
      responses:
        200:
          description: "successful operation"
          schema:
          $ref: "#/definitions/Connection"
        400:
          description: "Invalid input"
    patch:
      summary: "Patches an existing connection"
      description: ""
      operationId: "patchConnection"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "connection_id"
        description: "Connection object that needs to be patched"
        required: true
        type: integer
      - in: "body"
        name: "body"
        description: "New connection_type to be patched on Connection object"
        required: true
        schema:
          type: "object"
          properties:
            connection_type:
              type: string
      responses:
        200:
          description: "successful operation"
          schema:
              $ref: "#/definitions/Connection"
        400:
          description: "Invalid input"
        404:
          description: "Connection does not exist"
    delete:
      summary: "Delete an existing connection"
      description: ""
      operationId: "deleteConnection"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "connection_id"
        description: "The connection object that needs to be deleted"
        required: true
        type: integer
      responses:
        204:
          description: "Connection deleted"
        400:
          description: "Invalid input"
definitions:
  NewPerson:
    type: "object"
    properties:
      first_name:
        type: "string"
      last_name:
        type: "string"
      email:
        type: "string"
  Person:
    allOf:
      - type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      - $ref: "#/definitions/NewPerson"
  BaseConnection:
    type: "object"
    properties:
      connection_type:
        type: "string"
        description: "Connection Type"
        enum:
        - "mother"
        - "father"
        - "son"
        - "daughter"
        - "husband"
        - "wife"
        - "brother"
        - "sister"
        - "friend"
        - "coworker"
  NewConnection:
    allOf:
      - type: "object"
        properties:
          from_person_id:
            type: "integer"
            format: "int64"
            description: "From Person"
          to_person_id:
            type: "integer"
            format: "int64"
            description: "To Person"
      - $ref: "#/definitions/BaseConnection"
  Connection:
    allOf:
      - type: "object"
        properties:
          id:
            type: "integer"
            format: "int64"
      - $ref: "#/definitions/NewConnection"
  NestedConnection:
    allOf:
      - $ref: "#/definitions/BaseConnection"
      - type: "object"
        properties:
          id:
            type: "integer"
            format: "int64"
          from_person:
            $ref: "#/definitions/Person"
          to_person:
            $ref: "#/definitions/Person"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
